### ISSUE TITLE
As a player, I want to be able to manipulate every object with quest files so I can create quests.

### ISSUE THREAD

**Issue by nmradako** [GreenPandaStudios/project-dork#21]
- [x]  Maps can be created with .quest files
- [x]  Rooms can be created with .quest files
- [x] Room properties can be edited in .quest files
- [x]  Rooms can be connected to doorways in quest files
- [x]  Items can be created with .quest files
- [x]  item properties can be edited in .quest files
- [x] Usable items can be created with .quest files
- [x] Doorways can be created with .quest files
- [x] Doorway properties can be edited in .quest files
- [x] Keys can be created in .quest files
- [x] Key properties can be edited in .quest files
- [x] .quest files have meta-tags for defining quest charactersitics
- [x] .quest files have Notepad++ language to aid in writing code
- [x] Manual testing of Quest creation via .quest files conducted

**Comment by GreenPandaStudios** [comment]
Loading a valid .quest file that includes comments
![image](https://user-images.githubusercontent.com/72983234/141478279-21160f2a-d957-4f92-a36a-a131d4817533.png)

Referencing an item before it is created in a .quest file
![image](https://user-images.githubusercontent.com/72983234/141478548-39ef91fb-3fdb-49c6-bde0-5a903852b027.png)

Referencing a room before it is created in a .quest file
![image](https://user-images.githubusercontent.com/72983234/141478642-4289e233-0495-451c-a588-89ffdbb37af0.png)

Referencing a doorway before it is created in a .quest file
![image](https://user-images.githubusercontent.com/72983234/141478726-ed2bd594-1a76-4f46-a014-86cd025c118e.png)

Typing an invalid line in .quest file
![image](https://user-images.githubusercontent.com/72983234/141478852-b9767553-5ebc-4c14-a51f-de66fcbce203.png)
