### ISSUE TITLE
As a player, I want a merchant to have items and trade for certain amounts of gold so the value system has a use.

### ISSUE THREAD

**Issue by ztivnick** [GreenPandaStudios/project-dork#34]
- [x] Inventory system now has a "gold" spot
- [x] Gold contains no weight, only value
- [x] sell item to merchant command
- [x] buy item from merchant command
- [x] inspect item works with merchants inventory
- [x] inspect merchant displays the inventory items
- [x] sequence diagram
- [x] testing conducted

**Comment by GreenPandaStudios** [comment]
![image](https://user-images.githubusercontent.com/72983234/144298522-b4efdd4f-4417-418c-a381-f38f523a140b.png)
![image](https://user-images.githubusercontent.com/72983234/144298554-0781cbf1-4623-4e04-a9dc-e80c9a445cef.png)
